fix(ci): populate cache when it expired
haskell/security-advisories pull request #119
Opened 2023-08-28 18:26 UTC by blackheaven

2023-08-29 02:12 UTC, frasertweedale requested changes
Thanks, all makes sense.  I just request a couple of steps to have more descriptive names, and one typo fix.

2023-08-29 02:12 UTC, frasertweedale commented on .github/workflows/call-check-advisories.yml
> +      - name: Populate cache
Could you please change the name to "Populate cache on cache miss"?

2023-08-29 02:12 UTC, frasertweedale commented on .github/workflows/call-check-advisories.yml
> +      - name: Fetch cache
Could you please change the name to "Fetch cache (second attempt after cache miss)"?

2023-08-29 17:45 UTC, TristanCacqueray approved these changes

2023-08-30 05:15 UTC, frasertweedale approved these changes

2023-08-30 05:15 UTC, merged