hsec-sync: document usage
haskell/security-advisories pull request #225
Opened 2024-07-27 13:39 UTC by blackheaven

Adding documentation usage.

[Rendered](https://github.com/blackheaven/security-advisories/blob/sync/add-doc/code/hsec-sync/README.md)

/cc @Kleidukos

2024-07-27 13:48 UTC, Kleidukos requested changes

2024-07-27 13:48 UTC, Kleidukos commented on code/hsec-sync/README.md
> +[hsec-tools](../hsec-sync/) is the main entry point for dealing with [security advisories](https://github.com/haskell/security-advisories).
```suggestion
[hsec-tools](../hsec-tools/) is the main entry point for dealing with [security advisories](https://github.com/haskell/security-advisories).
```

2024-07-27 13:50 UTC, blackheaven commented
@Kleidukos thank you

2024-07-27 13:52 UTC, Kleidukos approved these changes

2024-07-30 11:06 UTC, frasertweedale commented
Thanks @blackheaven.  Thanks for reviewing it, @Kleidukos.  Merging.

2024-07-30 11:06 UTC, merged